# Generated by Django 5.1.3 on 2024-12-17 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('plannedBudget', models.FloatField()),
                ('spentBudget', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('item_checklist_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('planner_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('exp_type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(blank=True, null=True)),
                ('is_document', models.BooleanField()),
                ('is_vaccination', models.BooleanField()),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('place_to_visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tips', models.JSONField()),
                ('location', models.CharField(max_length=255)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planner')),
            ],
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='planner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.planner'),
        ),
        migrations.CreateModel(
            name='TransportSuggestions',
            fields=[
                ('transport_suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('affordability', models.CharField(max_length=50)),
                ('approximate_cost', models.CharField(max_length=50)),
                ('advantages', models.CharField(max_length=100)),
                ('disadvantages', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=100)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planner')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('accommodation', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('tripName', models.CharField(max_length=50)),
                ('tripDuration', models.IntegerField()),
                ('tripPreferences', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planner',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
        ),
        migrations.AddField(
            model_name='budget',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
        ),
    ]
